name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  skaffold:
    description: "skaffold"
    required: true
    default: "help"
runs:
  using: 'docker'
  image: 'Dockerfile'
